buildscript {
    repositories {
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
        maven { url 'https://repo.huaweicloud.com/repository/google/' }
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
