pluginManagement {
    repositories {
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
        maven { url 'https://repo.huaweicloud.com/repository/google/' }
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
        maven { url 'https://repo.huaweicloud.com/repository/google/' }
        google()
        mavenCentral()
    }
}
rootProject.name = "OmniAI-Assistant"
include ':app'
include ':model_feature'
